//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI_DSI.Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLESEXPOSICION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLESEXPOSICION()
        {
            this.DETALLESPOREXPOSICION = new HashSet<DETALLESPOREXPOSICION>();
        }
    
        public int Id_DetalleExposicion { get; set; }
        public string LugarAsignado { get; set; }
        public Nullable<int> Id_Obra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLESPOREXPOSICION> DETALLESPOREXPOSICION { get; set; }
        public virtual OBRAS OBRAS { get; set; }
    }
}
