//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI_DSI.Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAS
    {
        public int Id_Dia { get; set; }
        public string Nombre { get; set; }
    }
}
