//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI_DSI.Backend
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPAIEntities : DbContext
    {
        public PPAIEntities()
            : base("name=PPAIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASIGNACIONESVISITA> ASIGNACIONESVISITA { get; set; }
        public virtual DbSet<ASIGNACIONESVISITAPORRESERVA> ASIGNACIONESVISITAPORRESERVA { get; set; }
        public virtual DbSet<CAMBIOSESTADOS> CAMBIOSESTADOS { get; set; }
        public virtual DbSet<CAMBIOSESTADOSPORRESERVA> CAMBIOSESTADOSPORRESERVA { get; set; }
        public virtual DbSet<CARGOS> CARGOS { get; set; }
        public virtual DbSet<DETALLESEXPOSICION> DETALLESEXPOSICION { get; set; }
        public virtual DbSet<DIAS> DIAS { get; set; }
        public virtual DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual DbSet<ESCUELAS> ESCUELAS { get; set; }
        public virtual DbSet<ESTADOS> ESTADOS { get; set; }
        public virtual DbSet<EXPOSICIONES> EXPOSICIONES { get; set; }
        public virtual DbSet<EXPOSICIONESPORRESERVA> EXPOSICIONESPORRESERVA { get; set; }
        public virtual DbSet<EXPOSICIONESPORSEDE> EXPOSICIONESPORSEDE { get; set; }
        public virtual DbSet<HORARIOSTRABAJOS> HORARIOSTRABAJOS { get; set; }
        public virtual DbSet<OBRAS> OBRAS { get; set; }
        public virtual DbSet<OBRASPOREXPOSICION> OBRASPOREXPOSICION { get; set; }
        public virtual DbSet<PUBLICOSDESTINO> PUBLICOSDESTINO { get; set; }
        public virtual DbSet<RESERVAS> RESERVAS { get; set; }
        public virtual DbSet<SEDES> SEDES { get; set; }
        public virtual DbSet<SESION> SESION { get; set; }
        public virtual DbSet<TIPOSEXPOSICION> TIPOSEXPOSICION { get; set; }
        public virtual DbSet<TIPOSVISITA> TIPOSVISITA { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
