//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI_DSI.Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBRAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBRAS()
        {
            this.DETALLESEXPOSICION = new HashSet<DETALLESEXPOSICION>();
            this.OBRASPOREXPOSICION = new HashSet<OBRASPOREXPOSICION>();
        }
    
        public int Id_Obra { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaPrimerIngreso { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> DuracionExtendida { get; set; }
        public Nullable<int> DuracionResumida { get; set; }
        public Nullable<int> Alto { get; set; }
        public Nullable<int> Ancho { get; set; }
        public Nullable<int> Peso { get; set; }
        public Nullable<int> Valuacion { get; set; }
        public Nullable<int> CodigoSensor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLESEXPOSICION> DETALLESEXPOSICION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBRASPOREXPOSICION> OBRASPOREXPOSICION { get; set; }
    }
}
