//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI_DSI.Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVAS()
        {
            this.ASIGNACIONESVISITAPORRESERVA = new HashSet<ASIGNACIONESVISITAPORRESERVA>();
            this.CAMBIOSESTADOSPORRESERVA = new HashSet<CAMBIOSESTADOSPORRESERVA>();
            this.EXPOSICIONESPORRESERVA = new HashSet<EXPOSICIONESPORRESERVA>();
        }
    
        public int Id_Reserva { get; set; }
        public Nullable<int> DuracionEstimada { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public Nullable<System.DateTime> FechaReserva { get; set; }
        public Nullable<System.TimeSpan> HoraReserva { get; set; }
        public Nullable<System.TimeSpan> HoraInicioReal { get; set; }
        public Nullable<System.TimeSpan> HoraFinReal { get; set; }
        public Nullable<int> CantidadAlumnos { get; set; }
        public Nullable<int> CantidadAlumnosConfirmados { get; set; }
        public Nullable<int> Id_Sede { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> NroReserva { get; set; }
        public Nullable<int> Id_Escuela { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASIGNACIONESVISITAPORRESERVA> ASIGNACIONESVISITAPORRESERVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMBIOSESTADOSPORRESERVA> CAMBIOSESTADOSPORRESERVA { get; set; }
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual ESCUELAS ESCUELAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPOSICIONESPORRESERVA> EXPOSICIONESPORRESERVA { get; set; }
        public virtual SEDES SEDES { get; set; }
    }
}
