//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI_DSI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCUELAS
    {
        public int Id_Escuela { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Domicilio { get; set; }
        public Nullable<long> NroTelefono { get; set; }
    }
}
