//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI_DSI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESION
    {
        public int Id_Sesion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
