//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI_DSI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS()
        {
            this.ASIGNACIONESVISITA = new HashSet<ASIGNACIONESVISITA>();
            this.USUARIOS = new HashSet<USUARIOS>();
            this.RESERVAS = new HashSet<RESERVAS>();
        }
    
        public int Id_Empleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string CodigoValidacion { get; set; }
        public Nullable<long> Cuit { get; set; }
        public Nullable<int> Dni { get; set; }
        public string Domicilio { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public Nullable<long> NroTelefono { get; set; }
        public Nullable<int> Id_Cargo { get; set; }
        public Nullable<int> Id_HorarioTrabajo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASIGNACIONESVISITA> ASIGNACIONESVISITA { get; set; }
        public virtual CARGOS CARGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
        public virtual HORARIOSTRABAJOS HORARIOSTRABAJOS { get; set; }
    }
}
