//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPAI_DSI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVAS
    {
        public int Id_Reserva { get; set; }
        public Nullable<int> DuracionEstimada { get; set; }
        public Nullable<System.DateTime> FechaHoraCreacion { get; set; }
        public Nullable<System.TimeSpan> HoraInicioReal { get; set; }
        public Nullable<System.TimeSpan> HoraFinReal { get; set; }
        public Nullable<int> CantidadAlumnos { get; set; }
        public Nullable<int> CantidadAlumnosConfirmados { get; set; }
        public Nullable<int> Id_Sede { get; set; }
        public Nullable<int> Id_AsignacionVisita { get; set; }
        public Nullable<int> Id_Exposicion { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_CambioEstado { get; set; }
        public Nullable<System.DateTime> FechaReserva { get; set; }
    
        public virtual ASIGNACIONESVISITA ASIGNACIONESVISITA { get; set; }
        public virtual CAMBIOSESTADOS CAMBIOSESTADOS { get; set; }
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual EXPOSICIONES EXPOSICIONES { get; set; }
        public virtual SEDES SEDES { get; set; }
    }
}
